### ISSUE TITLE
Suggestion: Change the Heading Color 

### ISSUE THREAD

**Issue by Mathan7797** [Shakhthi/DevOps#1]
I think color of the heading is bit inappropriate to view.
Changing it may look better.

Changing rule can be like this:-

```css
h1 {
     color: #e79810;
     }
```
